# Importing Libraries

In [26]:
import pandas as pd
import numpy as np
from IPython.display import display
import seaborn as sns
import matplotlib.pylab as plt
import warnings
warnings.filterwarnings('ignore')

# Reading and copying the dataset

In [27]:
churn = pd.read_csv("Telco-Customer-Churn.csv")
print(churn.shape)
display(churn)
churn_cpy = churn.copy()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# Removing Duplicates

In [28]:
churn_cpy = churn_cpy.drop_duplicates()
display(churn_cpy)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# Dealing with Nulls

In [29]:
nulls = churn_cpy.isnull().sum().sort_values(ascending=False)
print(nulls)

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Features and Target

In [30]:
features_raw = churn_cpy.drop(['customerID'], axis = 1)
features_raw

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [31]:
features_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [32]:
features_raw['TotalCharges'] = pd.to_numeric(features_raw['TotalCharges'], errors='coerce')
features_raw

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [33]:
features_raw.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [34]:
features_raw = features_raw.dropna()
display(features_raw)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [35]:
features_raw.nunique()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                72
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1584
TotalCharges        6530
Churn                  2
dtype: int64

In [36]:
features_raw['gender'] = features_raw['gender'].map({'Female': 0, 'Male': 1})
features_raw

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,1,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,1,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,1,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,0,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,0,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,0,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,1,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,1,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

# Binary Columns

In [37]:
binary_columns = ['SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']

# Convert binary columns to 0 and 1
features_raw[binary_columns] = features_raw[binary_columns].replace({'Yes': 1, 'No': 0})
features_raw

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,No
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,No
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,Yes
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,No
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,1,Mailed check,84.80,1990.50,No
7039,0,0,1,1,72,1,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.90,No
7040,0,0,1,1,11,0,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,1,Electronic check,29.60,346.45,No
7041,1,1,1,0,4,1,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Mailed check,74.40,306.60,Yes
7042,1,0,0,0,66,1,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.50,No

In [38]:
features_raw.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Multicategory columns

In [39]:
# List of columns with more than two unique values
multi_category_columns = ['MultipleLines', 'InternetService', 'Contract',
                          'TechSupport', 'StreamingTV', 'StreamingMovies',
                          'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                          'PaymentMethod']

# Apply one-hot encoding
features = pd.get_dummies(features_raw, columns=multi_category_columns, drop_first=True)  # drop_first=True to avoid dummy variable trap
#print(features.to_string())
display(features)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,StreamingMovies_Yes,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,No,...,False,False,False,False,True,False,False,False,True,False
1,1,0,0,0,34,1,0,56.95,1889.50,No,...,False,False,True,False,False,False,True,False,False,True
2,1,0,0,0,2,1,1,53.85,108.15,Yes,...,False,False,True,False,True,False,False,False,False,True
3,1,0,0,0,45,0,0,42.30,1840.75,No,...,False,False,True,False,False,False,True,False,False,False
4,0,0,0,0,2,1,1,70.70,151.65,Yes,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,84.80,1990.50,No,...,True,False,True,False,False,False,True,False,False,True
7039,0,0,1,1,72,1,1,103.20,7362.90,No,...,True,False,False,False,True,False,True,True,False,False
7040,0,0,1,1,11,0,1,29.60,346.45,No,...,False,False,True,False,False,False,False,False,True,False
7041,1,1,1,0,4,1,1,74.40,306.60,Yes,...,False,False,False,False,False,False,False,False,False,True
7042,1,0,0,0,66,1,1,105.65,6844.50,No,...,True,False,True,False,False,False,True,False,False,False

In [40]:
display(features.nunique().to_string())

'gender                                      2\nSeniorCitizen                               2\nPartner                                     2\nDependents                                  2\ntenure                                     72\nPhoneService                                2\nPaperlessBilling                            2\nMonthlyCharges                           1584\nTotalCharges                             6530\nChurn                                       2\nMultipleLines_No phone service              2\nMultipleLines_Yes                           2\nInternetService_Fiber optic                 2\nInternetService_No                          2\nContract_One year                           2\nContract_Two year                           2\nTechSupport_No internet service             2\nTechSupport_Yes                             2\nStreamingTV_No internet service             2\nStreamingTV_Yes                             2\nStreamingMovies_No internet service         2\nStreamingMovies_Yes                         2\nOnlineSecurity_No internet service          2\nOnlineSecurity_Yes                          2\nOnlineBackup_No internet service            2\nOnlineBackup_Yes                            2\nDeviceProtection_No internet service        2\nDeviceProtection_Yes                        2\nPaymentMethod_Credit card (automatic)       2\nPaymentMethod_Electronic check              2\nPaymentMethod_Mailed check                  2'

# Converting boolean columns (True & False) into int (0 & 1)

In [41]:
# List of boolean columns to convert
boolean_columns = [
    'MultipleLines_No phone service',
    'MultipleLines_Yes',
    'InternetService_Fiber optic',
    'InternetService_No',
    'Contract_One year',
    'Contract_Two year',
    'TechSupport_No internet service',
    'TechSupport_Yes',
    'StreamingTV_No internet service',
    'StreamingTV_Yes',
    'StreamingMovies_No internet service',
    'StreamingMovies_Yes',
    'OnlineSecurity_No internet service',
    'OnlineSecurity_Yes',
    'OnlineBackup_No internet service',
    'OnlineBackup_Yes',
    'DeviceProtection_No internet service',
    'DeviceProtection_Yes',
    'PaymentMethod_Credit card (automatic)',
    'PaymentMethod_Electronic check',
    'PaymentMethod_Mailed check'
]


# Convert boolean values to 0 and 1
features[boolean_columns] = features[boolean_columns].astype(int)

# Display the updated DataFrame
display(features)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,StreamingMovies_Yes,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,No,...,0,0,0,0,1,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,No,...,0,0,1,0,0,0,1,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,Yes,...,0,0,1,0,1,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,No,...,0,0,1,0,0,0,1,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,Yes,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,84.80,1990.50,No,...,1,0,1,0,0,0,1,0,0,1
7039,0,0,1,1,72,1,1,103.20,7362.90,No,...,1,0,0,0,1,0,1,1,0,0
7040,0,0,1,1,11,0,1,29.60,346.45,No,...,0,0,1,0,0,0,0,0,1,0
7041,1,1,1,0,4,1,1,74.40,306.60,Yes,...,0,0,0,0,0,0,0,0,0,1
7042,1,0,0,0,66,1,1,105.65,6844.50,No,...,1,0,1,0,0,0,1,0,0,0

In [42]:
features['Churn'] = features['Churn'].map({'No': 0, 'Yes': 1})
features

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,StreamingMovies_Yes,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,1,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,1,0,0,0,1,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,1,0,1,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,0,0,1,0,0,0,1,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,84.80,1990.50,0,...,1,0,1,0,0,0,1,0,0,1
7039,0,0,1,1,72,1,1,103.20,7362.90,0,...,1,0,0,0,1,0,1,1,0,0
7040,0,0,1,1,11,0,1,29.60,346.45,0,...,0,0,1,0,0,0,0,0,1,0
7041,1,1,1,0,4,1,1,74.40,306.60,1,...,0,0,0,0,0,0,0,0,0,1
7042,1,0,0,0,66,1,1,105.65,6844.50,0,...,1,0,1,0,0,0,1,0,0,0

In [43]:
corr = features.corr()['Churn']
corr

gender                                  -0.008545
SeniorCitizen                            0.150541
Partner                                 -0.149982
Dependents                              -0.163128
tenure                                  -0.354049
PhoneService                             0.011691
PaperlessBilling                         0.191454
MonthlyCharges                           0.192858
TotalCharges                            -0.199484
Churn                                    1.000000
MultipleLines_No phone service          -0.011691
MultipleLines_Yes                        0.040033
InternetService_Fiber optic              0.307463
InternetService_No                      -0.227578
Contract_One year                       -0.178225
Contract_Two year                       -0.301552
TechSupport_No internet service         -0.227578
TechSupport_Yes                         -0.164716
StreamingTV_No internet service         -0.227578
StreamingTV_Yes                          0.063254
StreamingMovies_No internet service     -0.227578
StreamingMovies_Yes                      0.060860
OnlineSecurity_No internet service      -0.227578
OnlineSecurity_Yes                      -0.171270
OnlineBackup_No internet service        -0.227578
OnlineBackup_Yes                        -0.082307
DeviceProtection_No internet service    -0.227578
DeviceProtection_Yes                    -0.066193
PaymentMethod_Credit card (automatic)   -0.134687
PaymentMethod_Electronic check           0.301455
PaymentMethod_Mailed check              -0.090773
Name: Churn, dtype: float64

In [44]:
top_features = corr[(corr > 0.1) | (corr < - 0.1)].sort_values(ascending=False) #displays  correlation coefficient greater than 0.5
top_features = top_features.drop('Churn')
top_features.index

Index(['InternetService_Fiber optic', 'PaymentMethod_Electronic check',
       'MonthlyCharges', 'PaperlessBilling', 'SeniorCitizen',
       'PaymentMethod_Credit card (automatic)', 'Partner', 'Dependents',
       'TechSupport_Yes', 'OnlineSecurity_Yes', 'Contract_One year',
       'TotalCharges', 'OnlineSecurity_No internet service',
       'DeviceProtection_No internet service',
       'TechSupport_No internet service', 'InternetService_No',
       'StreamingTV_No internet service', 'OnlineBackup_No internet service',
       'StreamingMovies_No internet service', 'Contract_Two year', 'tenure'],
      dtype='object')

In [45]:
target = features['Churn']
target

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7032, dtype: int64

In [46]:
features.drop('Churn' ,axis=1 , inplace=True)
features = features[top_features.index]
features

,InternetService_Fiber optic,PaymentMethod_Electronic check,MonthlyCharges,PaperlessBilling,SeniorCitizen,PaymentMethod_Credit card (automatic),Partner,Dependents,TechSupport_Yes,OnlineSecurity_Yes,...,TotalCharges,OnlineSecurity_No internet service,DeviceProtection_No internet service,TechSupport_No internet service,InternetService_No,StreamingTV_No internet service,OnlineBackup_No internet service,StreamingMovies_No internet service,Contract_Two year,tenure
0,0,1,29.85,1,0,0,1,0,0,0,...,29.85,0,0,0,0,0,0,0,0,1
1,0,0,56.95,0,0,0,0,0,0,1,...,1889.50,0,0,0,0,0,0,0,0,34
2,0,0,53.85,1,0,0,0,0,0,1,...,108.15,0,0,0,0,0,0,0,0,2
3,0,0,42.30,0,0,0,0,0,1,1,...,1840.75,0,0,0,0,0,0,0,0,45
4,1,1,70.70,1,0,0,0,0,0,0,...,151.65,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,84.80,1,0,0,1,1,1,1,...,1990.50,0,0,0,0,0,0,0,0,24
7039,1,0,103.20,1,0,1,1,1,0,0,...,7362.90,0,0,0,0,0,0,0,0,72
7040,0,1,29.60,1,0,0,1,1,0,1,...,346.45,0,0,0,0,0,0,0,0,11
7041,1,0,74.40,1,1,0,1,0,0,0,...,306.60,0,0,0,0,0,0,0,0,4
7042,1,0,105.65,1,0,0,0,0,1,1,...,6844.50,0,0,0,0,0,0,0,1,66

# Splitting the data for training and testing

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=0)

In [48]:
target.value_counts() 
# There is class imbalance in the data

Churn
0    5163
1    1869
Name: count, dtype: int64

# After experimenting many models found best model : Random Forrest

# Random Forrest

### After tuning for long time using GridSearch here is the best model

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, accuracy_score
from sklearn.model_selection import ShuffleSplit
from imblearn.over_sampling import SMOTE

# Initialize the Random Forest Classifier with class weights
model = RandomForestClassifier(random_state=0,class_weight='balanced')

# Create the parameter grid
parameters = {
    'n_estimators': [230],          # Number of trees in the forest
    'max_depth': [10],               # Maximum depth of the tree
    'min_samples_split': [2],
    'min_samples_leaf': [2]               # Minimum number of samples required to split an internal node
}

# Set up cross-validation
cv_sets = ShuffleSplit(n_splits=5, random_state=0, test_size=0.2, train_size=None)

# Perform grid search on the classifier using F1 score as the scoring method
grid_rf = GridSearchCV(model, parameters, scoring='f1', cv=cv_sets)

# Fit the grid search object to the training data and find the optimal parameters
grid_rf.fit(X_train, y_train)

# Get the best estimator
best_rf = grid_rf.best_estimator_

# Fit the new model
best_rf.fit(X_train, y_train)

# Make predictions using the new model
best_train_predictions_rf = best_rf.predict(X_train)
best_test_predictions_rf = best_rf.predict(X_test)

# Calculate and print the F1 score and accuracy
print('Random Forest Training F1 Score:', f1_score(best_train_predictions_rf, y_train))
print('Random Forest Testing F1 Score:', f1_score(best_test_predictions_rf, y_test))
print('Random Forest Training Accuracy:', accuracy_score(y_train, best_train_predictions_rf))
print('Random Forest Testing Accuracy:', accuracy_score(y_test, best_test_predictions_rf))

# Explore what parameters ended up being used in the new model
print('Best Parameters:', grid_rf.best_params_)

Random Forest Training F1 Score: 0.7358916478555305
Random Forest Testing F1 Score: 0.6298850574712643
Random Forest Training Accuracy: 0.8336
Random Forest Testing Accuracy: 0.7711442786069652
Best Parameters: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 230}

In [50]:
# Function to check the output for a specific customer using Random Forest
def check_customer_output_by_index(customer_index, model, X_test, y_test=None):
    
        # Retrieve the customer's data by index
    customer_data = X_test.iloc[customer_index]

        # Reshape the data to be 2D for prediction
    customer_data = customer_data.values.reshape(1, -1)

        # Predict the outcome for the customer
    customer_prediction = best_rf.predict(customer_data)
    customer_proba = best_rf.predict_proba(customer_data)

        # Output the result
    print(f"Prediction for Customer at index {customer_index}: {customer_prediction[0]}")

        # If true labels exist, compare the prediction to the actual label
    if y_test is not None:
        actual_output = y_test.iloc[customer_index]
        print(f"Actual Output for Customer at index {customer_index}: {actual_output}")
    
    return customer_prediction , actual_output

# Example usage:
# Replace 'customer_index' with the row index of the customer in your test dataset

# Replace with the actual index of the customer you want to check
right , wrong = 0 , 0

for i in range(0,30):
    customer_index = i * 10
    customer_prediction , actual_output = check_customer_output_by_index(customer_index, model, X_test, y_test)
    if customer_prediction == actual_output :
        right = right + 1
    else :
        wrong = wrong + 1 

print()
print("Right = ",right)
print()
print("Wrong = ",wrong)

Prediction for Customer at index 0: 1
Actual Output for Customer at index 0: 0
Prediction for Customer at index 10: 0
Actual Output for Customer at index 10: 0
Prediction for Customer at index 20: 0
Actual Output for Customer at index 20: 0
Prediction for Customer at index 30: 0
Actual Output for Customer at index 30: 0
Prediction for Customer at index 40: 1
Actual Output for Customer at index 40: 0
Prediction for Customer at index 50: 1
Actual Output for Customer at index 50: 0
Prediction for Customer at index 60: 0
Actual Output for Customer at index 60: 0
Prediction for Customer at index 70: 0
Actual Output for Customer at index 70: 0
Prediction for Customer at index 80: 1
Actual Output for Customer at index 80: 0
Prediction for Customer at index 90: 1
Actual Output for Customer at index 90: 1
Prediction for Customer at index 100: 1
Actual Output for Customer at index 100: 1
Prediction for Customer at index 110: 0
Actual Output for Customer at index 110: 1
Prediction for Customer at index 120: 0
Actual Output for Customer at index 120: 0
Prediction for Customer at index 130: 0
Actual Output for Customer at index 130: 1
Prediction for Customer at index 140: 0
Actual Output for Customer at index 140: 1
Prediction for Customer at index 150: 0
Actual Output for Customer at index 150: 0
Prediction for Customer at index 160: 1
Actual Output for Customer at index 160: 0
Prediction for Customer at index 170: 0
Actual Output for Customer at index 170: 0
Prediction for Customer at index 180: 1
Actual Output for Customer at index 180: 1
Prediction for Customer at index 190: 1
Actual Output for Customer at index 190: 1
Prediction for Customer at index 200: 1
Actual Output for Customer at index 200: 1
Prediction for Customer at index 210: 1
Actual Output for Customer at index 210: 0
Prediction for Customer at index 220: 0
Actual Output for Customer at index 220: 0
Prediction for Customer at index 230: 1
Actual Output for Customer at index 230: 1
Prediction for Customer at index 240: 1
Actual Output for Customer at index 240: 1
Prediction for Customer at index 250: 1
Actual Output for Customer at index 250: 1
Prediction for Customer at index 260: 1
Actual Output for Customer at index 260: 1
Prediction for Customer at index 270: 0
Actual Output for Customer at index 270: 0
Prediction for Customer at index 280: 0
Actual Output for Customer at index 280: 0
Prediction for Customer at index 290: 0
Actual Output for Customer at index 290: 0

Right =  21

Wrong =  9